-- MySQL Script generated by MySQL Workbench
-- Mon Oct 21 20:38:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`IdUser`),
  UNIQUE INDEX `IdUser_UNIQUE` (`IdUser` ASC) VISIBLE,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  UNIQUE INDEX `Role_UNIQUE` (`Role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `IdRole` VARCHAR(1) NOT NULL,
  `RoleDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdRole`),
  UNIQUE INDEX `IdRole_UNIQUE` (`IdRole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonalData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonalData` (
  `IdUser` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Birthday` DATE NOT NULL,
  `PeselNumber` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `IdUser` INT NOT NULL,
  `IdClass` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teachers` (
  `IdUser` INT NOT NULL,
  `IdSchoolSub` INT NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SchoolSubjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SchoolSubjects` (
  `IdSchoolSub` INT NOT NULL AUTO_INCREMENT,
  `SchoolSubDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdSchoolSub`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marks` (
  `IdUser` INT NOT NULL,
  `IdSchoolSub` INT NOT NULL,
  `Mark` VARCHAR(1) NOT NULL,
  `DescMark` VARCHAR(45) NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LessonPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LessonPlan` (
  `IdClass` VARCHAR(2) NOT NULL,
  `Temetr` VARCHAR(1) NOT NULL,
  `Year` VARCHAR(4) NOT NULL,
  `Day` VARCHAR(1) NOT NULL,
  `IdSchoolSub01` INT NOT NULL,
  `IdSchoolSub02` INT NOT NULL,
  `IdSchoolSub03` INT NOT NULL,
  `IdSchoolSub04` INT NOT NULL,
  `IdSchoolSub05` INT NOT NULL,
  `IdSchoolSub06` INT NOT NULL,
  `IdSchoolSub07` INT NOT NULL,
  `IdSchoolSub08` INT NOT NULL,
  PRIMARY KEY (`IdClass`, `Temetr`, `Year`, `Day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderLessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderLessons` (
  `IdOrder` INT NOT NULL,
  `Start` TIME NOT NULL,
  `Finish` TIME NOT NULL,
  PRIMARY KEY (`IdOrder`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
